import Link from "next/link";
import PageHeroVideo from "@/components/PageHeroVideo";
import FloatingLogo from "@/components/FloatingLogo";

const offerings = [
  "Responsible AI assessments, governance frameworks, and policy alignment",
  "Domain-tuned copilots, agents, and retrieval augmented generation (RAG)",
  "Data engineering pipelines, feature stores, and vector-ready storage",
  "Prompt operations: evaluation harnesses, benchmarking, and drift monitoring",
  "Secure deployment: private endpoints, on-prem acceleration, and access controls",
];

const detailedOfferings = [
  {
    title: "Sales & Marketing",
    sections: [
      {
        heading: "Customer Acquisition & Engagement",
        bullets: [
          "Automated email campaigns (AI-written and personalized).",
          "AI-powered social media content creation and scheduling.",
          "Predictive lead scoring (identify leads most likely to convert).",
          "AI chatbots for websites to answer FAQs and book appointments.",
          "Dynamic pricing based on demand, season, inventory, etc.",
          "AI-generated ads (Google, Facebook, LinkedIn) optimized for conversions.",
        ],
      },
      {
        heading: "Content Creation",
        bullets: [
          "Automatically generate blog posts, newsletters, and scripts.",
          "Create product photos, marketing images, or explainer videos with AI.",
          "AI-driven SEO optimization and keyword analysis.",
        ],
      },
    ],
  },
  {
    title: "Operations & Productivity",
    sections: [
      {
        heading: "Automation",
        bullets: [
          "Automating repetitive office tasks (document creation, formatting, summaries).",
          "AI meeting transcriptions plus to-do extraction and follow-ups.",
          "Automated invoice processing (AP/AR), receipts, expense categorization.",
          "Scheduling automation (replacing Calendly-style tools).",
        ],
      },
      {
        heading: "Inventory & Supply Chain",
        bullets: [
          "Predictive inventory ordering.",
          "Demand forecasting to avoid overstock or understock.",
          "AI routing for delivery or service calls (efficient route planning).",
        ],
      },
    ],
  },
  {
    title: "Customer Service",
    sections: [
      {
        bullets: [
          "24/7 intelligent chatbots trained on company documents.",
          "AI voice agents (phone-based) for basic customer support.",
          "Automatic ticket triage and assignment.",
          "Sentiment analysis on customer emails and survey feedback.",
        ],
      },
    ],
  },
  {
    title: "HR & Workforce Management",
    sections: [
      {
        bullets: [
          "AI-assisted hiring (resume screening, skills matching).",
          "Automated onboarding with custom training modules generated by AI.",
          "Workforce scheduling optimization.",
          "AI-driven training and personalized learning paths.",
        ],
      },
    ],
  },
  {
    title: "Finance & Accounting",
    sections: [
      {
        bullets: [
          "Automated bookkeeping and reconciliation.",
          "Cash-flow forecasting models.",
          "Fraud detection (invoice anomalies, unusual transactions).",
          "AI-generated financial dashboards and projections.",
          "Automated tax document preparation or categorization.",
        ],
      },
    ],
  },
  {
    title: "IT, Engineering & Security (Great for Your Consulting Work)",
    sections: [
      {
        bullets: [
          "Automated code review (GitHub Copilot, CodeQL, AI SAST).",
          "Dependency scanning, CVE triage, severity scoring (Power BI dashboards).",
          "Automated infrastructure templates (IaC generation).",
          "Intelligent alerting to reduce noise in monitoring tools.",
          "AI agent assistants for L1–L2 support tasks.",
          "Risk scoring for vulnerabilities with AI prioritization.",
        ],
      },
    ],
  },
  {
    title: "Industry-Specific SMB Use Cases",
    sections: [
      {
        heading: "Healthcare Offices",
        bullets: [
          "AI scheduling (reduced no-shows).",
          "Automated prior authorization summaries.",
          "Medical transcription and coding suggestions.",
        ],
      },
      {
        heading: "Law Firms",
        bullets: [
          "Document review and summarization.",
          "Drafting briefs and client communications.",
          "Case research assistance.",
        ],
      },
      {
        heading: "Retail",
        bullets: [
          "Personalized product recommendations.",
          "Trend forecasting.",
          "Chat-based personal shopping assistant.",
        ],
      },
      {
        heading: "Construction / Trades",
        bullets: [
          "AI cost estimation.",
          "Material usage predictions.",
          "Site image analysis for safety compliance.",
        ],
      },
    ],
  },
  {
    title: "Customer Insights & Analytics",
    sections: [
      {
        bullets: [
          "Churn prediction (who is likely to leave).",
          "RFM customer segmentation (recency, frequency, value).",
          "AI-generated business intelligence dashboards.",
          "Insight summaries from CRM data (HubSpot, Salesforce, etc.).",
        ],
      },
    ],
  },
  {
    title: "Product & Innovation",
    sections: [
      {
        bullets: [
          "Generate prototypes, mockups, and wireframes based on idea descriptions.",
          "Market analysis and competitive research.",
          "New product ideas from trend analysis.",
        ],
      },
    ],
  },
  {
    title: "AI Assistants & Agents",
    sections: [
      {
        bullets: ["Custom AI assistants trained on company manuals, SOPs, and pricing sheets."],
      },
      {
        heading: "AI agents to",
        bullets: [
          "File documents.",
          "Pull sales reports.",
          "Update CRM entries.",
          "Monitor KPIs and alert when thresholds are exceeded.",
        ],
      },
    ],
  },
];

export default function AiServicesPage() {
  return (
    <main>
      <FloatingLogo />

      <PageHeroVideo
        folder="services/ai"
        title="AI/Machine Learning Services"
        subtitle="Translate AI hype into measurable outcomes with disciplined data practices and production-ready delivery."
      />

      <section className="container mx-auto px-6 md:px-10 lg:px-16 py-12 md:py-16 space-y-10 text-gray-200">
        <div className="space-y-6">
          <p className="text-sm uppercase tracking-[0.3em] text-[#37CC97]/80">Offerings</p>
          <h2 className="text-3xl font-semibold text-white">Where AI accelerates teams today</h2>
          <ol className="list-decimal pl-6 text-gray-300 space-y-6">
            {detailedOfferings.map((category) => (
              <li key={category.title} className="space-y-2">
                <p className="text-xl font-semibold text-white">{category.title}</p>
                <div className="space-y-3">
                  {category.sections.map((section) => (
                    <div key={`${category.title}-${section.heading ?? "general"}`} className="space-y-1">
                      {section.heading && (
                        <p className="font-semibold text-white">{section.heading}</p>
                      )}
                      <ul className="list-disc pl-6 space-y-1">
                        {section.bullets.map((bullet) => (
                          <li key={`${category.title}-${section.heading ?? "general"}-${bullet}`} className="text-gray-300">
                            {bullet}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </li>
            ))}
          </ol>
        </div>

        <div className="grid gap-8 md:grid-cols-[1.2fr_0.8fr]">
          <div className="space-y-6">
            <p className="text-sm uppercase tracking-[0.3em] text-[#37CC97]/80">Approach</p>
            <h1 className="text-3xl font-semibold text-white">AI that respects your data, users, and regulators</h1>
            <p className="text-gray-300">
              We guide organizations from ideation to production with a balanced focus on governance, human-centered design, and technical depth. Expect honest guidance about feasibility, total cost, and the change management required to land AI responsibly.
            </p>
            <p className="text-gray-300">
              Whether you need a lightweight proof of concept, an embedded enabling team, or a managed platform, we align model choice, infrastructure, and success metrics so you can defend ROI to leadership.
            </p>
          </div>
          <div className="rounded-3xl border border-white/10 bg-white/[0.03] p-6 space-y-4">
            <h2 className="text-xl font-semibold text-white">Signature services</h2>
            <ul className="list-disc pl-6 text-gray-300 space-y-2">
              {offerings.map((item) => (
                <li key={item}>{item}</li>
              ))}
            </ul>
            <Link
              href="/contact"
              className="inline-flex items-center justify-center rounded-2xl bg-[#37CC97] px-5 py-3 font-semibold text-black hover:bg-[#2ea77c]"
            >
              Schedule an AI workshop
            </Link>
          </div>
        </div>

        <div className="rounded-3xl border border-white/10 bg-white/[0.02] p-6 space-y-4">
          <h2 className="text-2xl font-semibold text-white">Typical engagement flow</h2>
          <ol className="list-decimal pl-6 text-gray-300 space-y-2">
            <li>Discovery sprints to map processes, data maturity, and responsible AI requirements.</li>
            <li>Use-case prioritization with measurable success metrics and stakeholder alignment.</li>
            <li>Pilot build-out (copilot, automation, or insights) with rapid evaluation loops.</li>
            <li>Production hardening: monitoring, alerts, fallback experiences, and enablement.</li>
            <li>Operational runbooks and change management support to scale across teams.</li>
          </ol>
        </div>
      </section>
    </main>
  );
}
